### ISSUE TITLE
when using dataset_visualization.py runing sometimes., this error occur?

### ISSUE THREAD

**Issue by zhangcj13** [prophesee-ai/prophesee-automotive-dataset-toolbox#20]
Is the python version occur this?
### .\src\io\psee_loader.py:139: RuntimeWarning: overflow encountered in long_scalars
  count = (min(self._end, pos + batch * self._ev_size) - pos) // self._ev_size
.\src\io\psee_loader.py:156: RuntimeWarning: overflow encountered in long_scalars
  self._file.seek(start + idx * self._ev_size)
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.1.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.1.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/prophesee_toolbox/dataset_visualization.py", line 86, in <module>
    play_files_parallel(ARGS.records, skip=ARGS.skip, delta_t=ARGS.delta_t)
  File "/prophesee_toolbox/dataset_visualization.py", line 52, in play_files_parallel
    events = [video.load_delta_t(delta_t) for video in videos]
  File "/prophesee_toolbox/dataset_visualization.py", line 52, in <listcomp>
    events = [video.load_delta_t(delta_t) for video in videos]
  File "\prophesee_toolbox\src\io\psee_loader.py", line 156, in load_delta_t
    self._file.seek(start + idx * self._ev_size)
OSError: [Errno 22] Invalid argument

**Comment by laurentbristiel** [comment]
This warning should not be related to Python version.
I think we are hitting the warning described in this page: https://stackoverflow.com/questions/7559595/python-runtimewarning-overflow-encountered-in-long-scalars
Could you share the command line you are launching (and what data you use) that leads to this warning?
